### ISSUE TITLE
Document default connector `variables`

### ISSUE THREAD

**Issue by CherfaElyes** [sentrysoftware/metricshub-community-connectors#128]
After adding the possibility to define default connector variables values, we need to update connectors.md to add the `variables` section in the examples:

```yaml
extends:
- ../System/System
connector:
  displayName: Linux - Processes (ps)
  platforms: Any Linux system
  reliesOn: Linux ps command
  information: Monitors performance metrics (CPU, memory, etc.) of the processes that match the specified criteria in `matchName`, `matchCommand`, and `matchUser`.
  detection:
    connectionTypes:
    - remote
    - local
    appliesTo:
    - linux
    disableAutoDetection: true
    criteria:
    - type: commandLine
      commandLine: /usr/bin/which ps || /bin/which ps
      expectedResult: /bin/ps
      errorMessage: Not a valid Linux host.
    tags: [ system, linux ]
  variables:
    matchName:
      description: Regular expression pattern to match process names for monitoring.
      defaultValue: .* 
    matchCommand:
      description: Regular expression pattern to match process command lines for monitoring.
      defaultValue: .*
    matchUser:
      description: Regular expression pattern to match process users for inclusion.
      defaultValue: .*
```
