### ISSUE TITLE
Add a new metric for Memory Utilization in Hardware.yaml

### ISSUE THREAD

**Issue by TNohaic** [sentrysoftware/metricshub-community-connectors#150]
### Specifications
Add a new metric in Hardware.yaml:
```
  hw.memory.utilization:
    description: Fraction of memory used.
    type: Gauge
    unit: 1
```
