### ISSUE TITLE
Update constant references for better clarity

### ISSUE THREAD

**Issue by NassimBtk** [sentrysoftware/metricshub-community-connectors#31]
# Specification

Constants should be referred to with `${constant::<constant_name>}` for clarity and consistency.

Example: 
```yaml
        source(1):
          # Get the model name
          # ModelName;SerialNumber;DeviceSlotID;
          type: snmpTable
          oid: 1.3.6.1.4.1.${constant::_OID}.2.235.1.1.1
```

Update the constants referenced in the community connector using the new pattern: `${constant::<constant_name>}` where the `<constant_name>` is the old value of the constant in the existing community connectors.
