### ISSUE TITLE
MIB2NT: Bad ExcludeMatchingLines regex

### ISSUE THREAD

**Issue by NassimBtk** [sentrysoftware/metricshub-community-connectors#95]
### Specification

In the MI2BNT connector, the `ExcludeMatchingLines` regex is incorrect. The double quotes are missing, leading to a bad regex where the job will continue to include unwanted monitors.

Current incorrect configuration:
```yaml
         - type: excludeMatchingLines
            column: 2
            regExp: \\(WAN\\)\\|\\(QoS\\)\\|\\([Ff]ilter\\)\\|\\([Ss]witch\\)\\|\\(57 41 4E 20\\)\\|\\(4D 69 63 72 6F 73 6F 66 74\\)
```

Correct configuration:
```yaml
         - type: excludeMatchingLines
            column: 2
            regExp: "\\(WAN\\)\\|\\(QoS\\)\\|\\([Ff]ilter\\)\\|\\([Ss]witch\\)\\|\\(57 41 4E 20\\)\\|\\(4D 69 63 72 6F 73 6F 66 74\\)"
```
